"""Render compatibility requirement files from pyproject.toml.

The project metadata is the only editable dependency manifest. The generated
files remain available for contributors that use ``pip -r``. Release builds use
the hashed PEP 751 ``pylock.toml`` generated by ``tools/lock_requirements.py``.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10
    import tomli as tomllib


ROOT = Path(__file__).resolve().parents[1]
PYPROJECT = ROOT / "pyproject.toml"


def _header(group: str) -> str:
    command = "python tools/sync_requirements.py"
    return (
        "# Generated from pyproject.toml. Do not edit this file directly.\n"
        f"# Dependency group: {group}\n"
        f"# Regenerate with: {command}\n\n"
    )


def render_files() -> dict[Path, str]:
    with PYPROJECT.open("rb") as handle:
        project = tomllib.load(handle)["project"]

    runtime = "\n".join(project["dependencies"]) + "\n"
    development = "\n".join(project["optional-dependencies"]["dev"]) + "\n"
    return {
        ROOT / "requirements.in": _header("runtime") + runtime,
        ROOT / "requirements.txt": _header("runtime") + runtime,
        ROOT / "requirements-dev.in": _header("development") + development,
    }


def sync(*, check: bool = False) -> int:
    stale: list[Path] = []
    for path, expected in render_files().items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == expected:
            continue
        if check:
            stale.append(path)
        else:
            path.write_text(expected, encoding="utf-8", newline="\n")

    if stale:
        names = ", ".join(path.name for path in stale)
        print(f"Requirement files out of date: {names}")
        print("Run: python tools/sync_requirements.py")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()
    return sync(check=args.check)


if __name__ == "__main__":
    sys.exit(main())
